# Generated by Django 4.2.3 on 2023-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbook', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='guests', to='eventbook.event'),
        ),
    ]
