# Generated by Django 4.2.3 on 2023-07-05 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbook', '0003_alter_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='events_guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
