# Generated by Django 4.2.3 on 2023-07-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbook', '0005_remove_event_guests_event_going_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
